description: ''
name: Chart
options:
  showDataLabels: false
  direction:
    type: counterclockwise
  missingValuesAsZero: false
  error_y:
    visible: true
    type: data
  numberFormat: 0,0[.]00000
  yAxis:
  - type: linear
    rangeMin: null
    title:
      text: '[KW, KWh]'
  - rangeMax: 100
    type: linear
    rangeMin: -30
    opposite: true
    title:
      text: Temperatura
  series:
    stacking: null
    percentValues: false
    error_y:
      visible: true
      type: data
  globalSeriesType: line
  percentFormat: 0[.]00%
  sortX: true
  seriesOptions:
    min_temperature_c:
      zIndex: 2
      index: 0
      type: line
      yAxis: 1
    energy_kwh:
      zIndex: 1
      index: 0
      type: line
      yAxis: 0
    max_temperature_c:
      zIndex: 3
      index: 0
      type: line
      yAxis: 1
    power_kw:
      zIndex: 0
      index: 0
      type: line
      yAxis: 0
    avg_temperature_c:
      zIndex: 4
      index: 0
      type: line
      yAxis: 1
  valuesOptions: {}
  xAxis:
    labels:
      enabled: true
    type: '-'
  dateTimeFormat: DD/MM/YY HH:mm
  columnMapping:
    min_temperature_c: y
    max_temperature_c: y
    power_kw: y
    energy_kwh: y
    avg_temperature_c: y
    time: x
  textFormat: ''
  customCode: '// Available variables are x, ys, element, and Plotly

    // Type console.log(x, ys); for more info about x and ys

    // To plot your graph call Plotly.plot(element, ...)

    // Plotly examples and docs: https://plot.ly/javascript/'
  legend:
    enabled: true
type: CHART
