description: ''
name: Potència, Energia i Temperatures d'inversors
options:
  showDataLabels: false
  direction:
    type: counterclockwise
  missingValuesAsZero: false
  error_y:
    visible: true
    type: data
  numberFormat: 0,0[.]00000
  yAxis:
  - type: linear
  - type: linear
    opposite: true
  series:
    stacking: null
    error_y:
      visible: true
      type: data
  globalSeriesType: scatter
  percentFormat: 0[.]00%
  sortX: true
  seriesOptions:
    inversor1:
      zIndex: 3
      index: 0
      type: scatter
      yAxis: 0
    inversor3:
      zIndex: 1
      index: 0
      type: scatter
      yAxis: 0
    inversor2:
      zIndex: 2
      index: 0
      type: scatter
      yAxis: 0
    inversor4:
      zIndex: 0
      index: 0
      type: scatter
      yAxis: 0
    Tots els inversors:
      zIndex: 4
      index: 0
      type: scatter
      yAxis: 1
  valuesOptions: {}
  xAxis:
    labels:
      enabled: true
    type: '-'
  dateTimeFormat: DD/MM/YY HH:mm
  columnMapping:
    inverter: series
    metric: y
    time: x
  textFormat: ''
  customCode: '// Available variables are x, ys, element, and Plotly

    // Type console.log(x, ys); for more info about x and ys

    // To plot your graph call Plotly.plot(element, ...)

    // Plotly examples and docs: https://plot.ly/javascript/'
  legend:
    enabled: true
type: CHART
