description: ''
name: Chart
options:
  showDataLabels: false
  direction:
    type: counterclockwise
  missingValuesAsZero: true
  error_y:
    visible: true
    type: data
  numberFormat: 0,0[.]00000
  yAxis:
  - type: linear
    title:
      text: Potència [W]
  - type: linear
    opposite: true
  series:
    stacking: null
    error_y:
      visible: true
      type: data
  globalSeriesType: line
  percentFormat: 0[.]00%
  sortX: true
  seriesOptions:
    inversor1:
      zIndex: 0
      index: 0
      type: line
      yAxis: 0
    inversor3:
      zIndex: 2
      index: 0
      type: line
      yAxis: 0
    inversor2:
      zIndex: 1
      index: 0
      type: line
      yAxis: 0
    'null':
      zIndex: 4
      index: 0
      type: line
      name: Total
      yAxis: 0
    inversor4:
      zIndex: 3
      index: 0
      type: line
      yAxis: 0
  valuesOptions: {}
  xAxis:
    labels:
      enabled: true
    type: '-'
  dateTimeFormat: DD/MM/YY HH:mm
  columnMapping:
    temps: x
    inverter: series
    potencia_w: y
  textFormat: ''
  customCode: '// Available variables are x, ys, element, and Plotly

    // Type console.log(x, ys); for more info about x and ys

    // To plot your graph call Plotly.plot(element, ...)

    // Plotly examples and docs: https://plot.ly/javascript/'
  legend:
    enabled: true
type: CHART
