description: ''
name: Chart
options:
  showDataLabels: false
  direction:
    type: counterclockwise
  missingValuesAsZero: false
  error_y:
    visible: true
    type: data
  numberFormat: 0,0[.]00000
  yAxis:
  - type: linear
    title:
      text: Energia [kWh]
  - type: linear
    opposite: true
  series:
    stacking: null
    error_y:
      visible: true
      type: data
  globalSeriesType: line
  percentFormat: 0[.]00%
  sortX: true
  seriesOptions:
    Sat Sep 25 2021 17:05:08 GMT+0000:
      zIndex: 3
      index: 0
      type: line
      yAxis: 0
    Wed Sep 22 2021 17:05:06 GMT+0000:
      zIndex: 1
      index: 0
      type: line
      yAxis: 0
    Wed Sep 22 2021 13:22:14 GMT+0000:
      zIndex: 0
      index: 0
      type: line
      yAxis: 0
    Mon Sep 27 2021 17:05:08 GMT+0000:
      zIndex: 5
      index: 0
      type: line
      yAxis: 0
    Tue Sep 28 2021 17:05:07 GMT+0000:
      zIndex: 6
      index: 0
      type: line
      yAxis: 0
    Fri Sep 24 2021 17:05:08 GMT+0000:
      zIndex: 2
      index: 0
      type: line
      yAxis: 0
    Sun Sep 26 2021 17:05:06 GMT+0000:
      zIndex: 4
      index: 0
      type: line
      yAxis: 0
  valuesOptions: {}
  xAxis:
    labels:
      enabled: true
    type: '-'
  dateTimeFormat: DD/MM/YY HH:mm
  columnMapping:
    energy_kwh: y
    time: x
    forecastdate: series
  textFormat: ''
  customCode: |-
    // Available variables are x, ys, element, and Plotly
    // Type console.log(x, ys); for more info about x and ys
    // To plot your graph call Plotly.plot(element, ...)
    // Plotly examples and docs: https://plot.ly/javascript/
  legend:
    enabled: true
type: CHART
