SELECT 'Energes Gamma Blanco' AS nom_societat,
       'Fotovoltaica' AS tecnologia,
       'PV Vallehermoso' AS plant_name,
       'Alcolea del Rio, 41449, Sevilla' AS plant_location,
       '2.16 MWp' AS potencia_pic,
       '1.89 MW' AS potencia_nominal,
       37.628415 AS lat,
       -5.680599 AS long,
       '2016-05-06'::date AS grid_connection_time,
       '4 / 500 kW / Aros' AS inversors,
       '8640 / 250 Wp / Exiom' AS moduls,
       432 AS num_plant_strings,
       108 AS num_strings_inversor,
       20 AS num_modules_string;

