datasource:
  1: datasources/plantmonitor.yaml
  2: datasources/redash-query-results.yaml
query:
  28: queries/metriques-d-inversor-v2-una-metrica
  27: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup
  25: queries/metriques-d-inversor-v2-dropdown-per-metrica
  24: queries/all-plant-inverters-by-id
  23: queries/metriques-d-inversor
  19: queries/metriques-de-comptador
  17: queries/all-plants-by-id
  15: queries/dades-d-inversor
  13: queries/energia-exportada-comptadors-diaria
  12: queries/potencia-tots-els-inversors-amb-temps-i-granularitat
  11: queries/energia-acumulada
  10: queries/plant-overview
  9: queries/exportada-pr
  8: queries/sonda-d-irradiacio-actual
  7: queries/potencia-activa-inversors-actual
  6: queries/alarma-de-comptador
  5: queries/all-plants
  4: queries/sonda-d-irradiacio
  3: queries/potencia-inversors-amb-total
  32: queries/new-query
  31: queries/energia-diaria-total-inversors
  30: queries/new-query-2
  29: queries/numero-de-lectures-d-inversor
visualization:
  44: queries/metriques-d-inversor-v2-una-metrica/visualizations/table.yaml
  45: queries/metriques-d-inversor-v2-una-metrica/visualizations/chart.yaml
  42: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup/visualizations/table.yaml
  43: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup/visualizations/chart.yaml
  38: queries/metriques-d-inversor-v2-dropdown-per-metrica/visualizations/table.yaml
  40: queries/metriques-d-inversor-v2-dropdown-per-metrica/visualizations/chart.yaml
  37: queries/all-plant-inverters-by-id/visualizations/table.yaml
  35: queries/metriques-d-inversor/visualizations/table.yaml
  36: queries/metriques-d-inversor/visualizations/chart.yaml
  30: queries/metriques-de-comptador/visualizations/table.yaml
  32: queries/metriques-de-comptador/visualizations/chart.yaml
  27: queries/all-plants-by-id/visualizations/table.yaml
  25: queries/dades-d-inversor/visualizations/table.yaml
  28: queries/dades-d-inversor/visualizations/chart.yaml
  23: queries/energia-exportada-comptadors-diaria/visualizations/energia-diaria.yaml
  22: queries/energia-exportada-comptadors-diaria/visualizations/table.yaml
  20: queries/potencia-tots-els-inversors-amb-temps-i-granularitat/visualizations/table.yaml
  21: queries/potencia-tots-els-inversors-amb-temps-i-granularitat/visualizations/chart.yaml
  18: queries/energia-acumulada/visualizations/table.yaml
  19: queries/energia-acumulada/visualizations/produccio-acumulada.yaml
  16: queries/plant-overview/visualizations/table.yaml
  17: queries/plant-overview/visualizations/details-view.yaml
  14: queries/exportada-pr/visualizations/table.yaml
  15: queries/exportada-pr/visualizations/chart.yaml
  12: queries/sonda-d-irradiacio-actual/visualizations/table.yaml
  13: queries/sonda-d-irradiacio-actual/visualizations/sonda-irradiacio-details-view.yaml
  10: queries/potencia-activa-inversors-actual/visualizations/table.yaml
  11: queries/potencia-activa-inversors-actual/visualizations/potencia-activa.yaml
  8: queries/alarma-de-comptador/visualizations/table.yaml
  9: queries/alarma-de-comptador/visualizations/details-view.yaml
  7: queries/all-plants/visualizations/table.yaml
  5: queries/sonda-d-irradiacio/visualizations/table.yaml
  6: queries/sonda-d-irradiacio/visualizations/chart.yaml
  3: queries/potencia-inversors-amb-total/visualizations/table.yaml
  4: queries/potencia-inversors-amb-total/visualizations/chart.yaml
  52: queries/new-query/visualizations/chart.yaml
  51: queries/new-query/visualizations/table.yaml
  49: queries/energia-diaria-total-inversors/visualizations/table.yaml
  50: queries/energia-diaria-total-inversors/visualizations/energia-diaria.yaml
  48: queries/new-query-2/visualizations/table.yaml
  46: queries/numero-de-lectures-d-inversor/visualizations/table.yaml
  47: queries/numero-de-lectures-d-inversor/visualizations/chart.yaml
dashboard:
  4: dashboards/dashboard-dinamic-de-planta
  2: dashboards/dashboard-general-de-planta
  1: dashboards/grafiques-puntuals
widget:
  16: dashboards/dashboard-dinamic-de-planta/widgets/widget.yaml
  18: dashboards/dashboard-dinamic-de-planta/widgets/widget-2.yaml
  24: dashboards/dashboard-dinamic-de-planta/widgets/widget-3.yaml
  22: dashboards/dashboard-dinamic-de-planta/widgets/widget-4.yaml
  7: dashboards/dashboard-general-de-planta/widgets/widget.yaml
  8: dashboards/dashboard-general-de-planta/widgets/widget-2.yaml
  10: dashboards/dashboard-general-de-planta/widgets/widget-3.yaml
  11: dashboards/dashboard-general-de-planta/widgets/widget-4.yaml
  12: dashboards/dashboard-general-de-planta/widgets/widget-5.yaml
  4: dashboards/dashboard-general-de-planta/widgets/widget-6.yaml
  5: dashboards/dashboard-general-de-planta/widgets/widget-7.yaml
  6: dashboards/dashboard-general-de-planta/widgets/widget-8.yaml
  9: dashboards/dashboard-general-de-planta/widgets/widget-9.yaml
  2: dashboards/grafiques-puntuals/widgets/widget.yaml
  3: dashboards/grafiques-puntuals/widgets/widget-2.yaml
  30: dashboards/dashboard-general-de-planta/widgets/widget-10.yaml
  25: dashboards/grafiques-puntuals/widgets/widget-3.yaml
