datasource:
  1: datasources/plantmonitor.yaml
  2: datasources/redash-query-results.yaml
query:
  28: queries/metriques-d-inversor-v2-una-metrica
  27: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup
  25: queries/metriques-d-inversor-v2-dropdown-per-metrica
  24: queries/all-plant-inverters-by-id
  23: queries/metriques-d-inversor
  19: queries/metriques-de-comptador
  17: queries/all-plants-by-id
  15: queries/dades-d-inversor
  13: queries/energia-exportada-comptadors-diaria
  12: queries/potencia-tots-els-inversors-amb-temps-i-granularitat
  11: queries/energia-acumulada
  10: queries/plant-overview
  9: queries/exportada-pr
  8: queries/sonda-d-irradiacio-actual
  7: queries/potencia-activa-inversors-actual
  6: queries/alarma-de-comptador
  5: queries/all-plants
  4: queries/sonda-d-irradiacio
  3: queries/potencia-inversors-amb-total
  32: queries/new-query
  31: queries/energia-diaria-total-inversors
  30: queries/new-query-2
  29: queries/numero-de-lectures-d-inversor
  37: queries/metriques-de-comptadors-base-query
  36: queries/hd-daily-via-redash
  35: queries/pr-amb-granularitat
  34: queries/pr-mensual-via-redash
  33: queries/pr-horari
  38: queries/metriques-mensuals-de-comptadors
  40: queries/potencia-esperada
  39: queries/energia-esperada-i-energia-perduda
  55: queries/produccion-respecto-a-objetivos
  54: queries/energia-importada-mensual
  53: queries/disponibilitat-amb-granularitat
  52: queries/new-query-3
  51: queries/energia-mensual-inversor
  50: queries/hores-equivalents-mensuals-i-energia-comptadors
  49: queries/cos-phi-horari-debug
  48: queries/cos-phi-mensual
  47: queries/potencia-total-inversors-irradiacio-potencia-esperada
  46: queries/potencia-total-inversors-irradiacio-potencia-esperada-amb-rollup
  45: queries/new-query-4
  44: queries/energia-esperada
  43: queries/irradiancia-i-irradiacio
  42: queries/potencia-esperada-i-energia-esperada-instantania
  41: queries/potencia-esperada-i-energia-esperada-horaria
  56: queries/produccion-respecto-inversor
  65: queries/copy-of-23-metriques-d-inversor
  64: queries/prediccio-meteologica
  63: queries/combine-date-trunc-and-month-from-target-energy
  62: queries/pr-con-granularidad-objetivos-historicos
  61: queries/energia-objetivo-alcolea
  60: queries/comparativa-inversores-diaria
  59: queries/comparativa-inversores-diaria-2
  58: queries/irradiacion-mensual
  57: queries/produccio-respecte-previsio
  70: queries/alarmas-de-dispositivos
  69: queries/alarma-sondas
  68: queries/alarma-de-inversores
  67: queries/prediccio-energia-mensual
  66: queries/new-query-5
visualization:
  44: queries/metriques-d-inversor-v2-una-metrica/visualizations/table.yaml
  45: queries/metriques-d-inversor-v2-una-metrica/visualizations/chart.yaml
  42: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup/visualizations/table.yaml
  43: queries/metriques-d-inversor-v2-dropdown-per-metrica-amb-rollup/visualizations/chart.yaml
  38: queries/metriques-d-inversor-v2-dropdown-per-metrica/visualizations/table.yaml
  40: queries/metriques-d-inversor-v2-dropdown-per-metrica/visualizations/chart.yaml
  37: queries/all-plant-inverters-by-id/visualizations/table.yaml
  35: queries/metriques-d-inversor/visualizations/table.yaml
  36: queries/metriques-d-inversor/visualizations/chart.yaml
  30: queries/metriques-de-comptador/visualizations/table.yaml
  32: queries/metriques-de-comptador/visualizations/chart.yaml
  27: queries/all-plants-by-id/visualizations/table.yaml
  25: queries/dades-d-inversor/visualizations/table.yaml
  28: queries/dades-d-inversor/visualizations/chart.yaml
  23: queries/energia-exportada-comptadors-diaria/visualizations/energia-diaria.yaml
  22: queries/energia-exportada-comptadors-diaria/visualizations/table.yaml
  20: queries/potencia-tots-els-inversors-amb-temps-i-granularitat/visualizations/table.yaml
  21: queries/potencia-tots-els-inversors-amb-temps-i-granularitat/visualizations/chart.yaml
  18: queries/energia-acumulada/visualizations/table.yaml
  19: queries/energia-acumulada/visualizations/produccio-acumulada.yaml
  16: queries/plant-overview/visualizations/table.yaml
  17: queries/plant-overview/visualizations/details-view.yaml
  14: queries/exportada-pr/visualizations/table.yaml
  15: queries/exportada-pr/visualizations/chart.yaml
  12: queries/sonda-d-irradiacio-actual/visualizations/table.yaml
  13: queries/sonda-d-irradiacio-actual/visualizations/sonda-irradiacio-details-view.yaml
  10: queries/potencia-activa-inversors-actual/visualizations/table.yaml
  11: queries/potencia-activa-inversors-actual/visualizations/potencia-activa.yaml
  8: queries/alarma-de-comptador/visualizations/table.yaml
  9: queries/alarma-de-comptador/visualizations/details-view.yaml
  7: queries/all-plants/visualizations/table.yaml
  5: queries/sonda-d-irradiacio/visualizations/table.yaml
  6: queries/sonda-d-irradiacio/visualizations/chart.yaml
  3: queries/potencia-inversors-amb-total/visualizations/table.yaml
  4: queries/potencia-inversors-amb-total/visualizations/chart.yaml
  52: queries/new-query/visualizations/chart.yaml
  51: queries/new-query/visualizations/table.yaml
  49: queries/energia-diaria-total-inversors/visualizations/table.yaml
  50: queries/energia-diaria-total-inversors/visualizations/energia-diaria.yaml
  48: queries/new-query-2/visualizations/table.yaml
  46: queries/numero-de-lectures-d-inversor/visualizations/table.yaml
  47: queries/numero-de-lectures-d-inversor/visualizations/chart.yaml
  58: queries/metriques-de-comptadors-base-query/visualizations/table.yaml
  57: queries/hd-daily-via-redash/visualizations/table.yaml
  56: queries/pr-amb-granularitat/visualizations/chart.yaml
  55: queries/pr-amb-granularitat/visualizations/table.yaml
  54: queries/pr-mensual-via-redash/visualizations/table.yaml
  53: queries/pr-horari/visualizations/table.yaml
  59: queries/metriques-mensuals-de-comptadors/visualizations/table.yaml
  63: queries/potencia-esperada/visualizations/chart.yaml
  62: queries/potencia-esperada/visualizations/table.yaml
  61: queries/energia-esperada-i-energia-perduda/visualizations/chart.yaml
  60: queries/energia-esperada-i-energia-perduda/visualizations/table.yaml
  85: queries/produccion-respecto-a-objetivos/visualizations/table.yaml
  84: queries/energia-importada-mensual/visualizations/table.yaml
  82: queries/disponibilitat-amb-granularitat/visualizations/table.yaml
  83: queries/disponibilitat-amb-granularitat/visualizations/chart.yaml
  81: queries/new-query-3/visualizations/table.yaml
  80: queries/energia-mensual-inversor/visualizations/table.yaml
  79: queries/hores-equivalents-mensuals-i-energia-comptadors/visualizations/table.yaml
  78: queries/cos-phi-horari-debug/visualizations/table.yaml
  77: queries/cos-phi-mensual/visualizations/table.yaml
  75: queries/potencia-total-inversors-irradiacio-potencia-esperada/visualizations/table.yaml
  76: queries/potencia-total-inversors-irradiacio-potencia-esperada/visualizations/chart.yaml
  73: queries/potencia-total-inversors-irradiacio-potencia-esperada-amb-rollup/visualizations/table.yaml
  74: queries/potencia-total-inversors-irradiacio-potencia-esperada-amb-rollup/visualizations/chart.yaml
  72: queries/new-query-4/visualizations/table.yaml
  70: queries/energia-esperada/visualizations/table.yaml
  71: queries/energia-esperada/visualizations/chart.yaml
  68: queries/irradiancia-i-irradiacio/visualizations/table.yaml
  69: queries/irradiancia-i-irradiacio/visualizations/chart.yaml
  67: queries/potencia-esperada-i-energia-esperada-instantania/visualizations/chart.yaml
  66: queries/potencia-esperada-i-energia-esperada-instantania/visualizations/table.yaml
  65: queries/potencia-esperada-i-energia-esperada-horaria/visualizations/chart.yaml
  64: queries/potencia-esperada-i-energia-esperada-horaria/visualizations/table.yaml
  86: queries/produccion-respecto-inversor/visualizations/table.yaml
  99: queries/copy-of-23-metriques-d-inversor/visualizations/table.yaml
  100: queries/copy-of-23-metriques-d-inversor/visualizations/chart.yaml
  97: queries/prediccio-meteologica/visualizations/table.yaml
  98: queries/prediccio-meteologica/visualizations/chart.yaml
  96: queries/combine-date-trunc-and-month-from-target-energy/visualizations/table.yaml
  94: queries/pr-con-granularidad-objetivos-historicos/visualizations/table.yaml
  92: queries/energia-objetivo-alcolea/visualizations/table.yaml
  90: queries/comparativa-inversores-diaria/visualizations/table.yaml
  91: queries/comparativa-inversores-diaria/visualizations/chart.yaml
  89: queries/comparativa-inversores-diaria-2/visualizations/table.yaml
  88: queries/irradiacion-mensual/visualizations/table.yaml
  87: queries/produccio-respecte-previsio/visualizations/table.yaml
  95: queries/pr-amb-granularitat/visualizations/produccio-i-pr-vs-objectius.yaml
  93: queries/metriques-d-inversor-v2-una-metrica/visualizations/inversors-energia-wh.yaml
  101: queries/pr-con-granularidad-objetivos-historicos/visualizations/produccion-i-pr-vs-objetivos-vs-historicos-vs-horas-equivalentes.yaml
  107: queries/alarmas-de-dispositivos/visualizations/table.yaml
  106: queries/alarma-sondas/visualizations/table.yaml
  105: queries/alarma-de-inversores/visualizations/table.yaml
  103: queries/prediccio-energia-mensual/visualizations/table.yaml
  102: queries/new-query-5/visualizations/table.yaml
dashboard:
  4: dashboards/dashboard-dinamic-de-planta
  2: dashboards/dashboard-general-de-planta
  1: dashboards/grafiques-puntuals
  7: dashboards/sandbox
  8: dashboards/dashboard-combinat
widget:
  16: dashboards/dashboard-dinamic-de-planta/widgets/widget.yaml
  18: dashboards/dashboard-dinamic-de-planta/widgets/widget-2.yaml
  24: dashboards/dashboard-dinamic-de-planta/widgets/widget-3.yaml
  22: dashboards/dashboard-dinamic-de-planta/widgets/widget-4.yaml
  7: dashboards/dashboard-general-de-planta/widgets/widget.yaml
  8: dashboards/dashboard-general-de-planta/widgets/widget-2.yaml
  10: dashboards/dashboard-general-de-planta/widgets/widget-3.yaml
  11: dashboards/dashboard-general-de-planta/widgets/widget-4.yaml
  12: dashboards/dashboard-general-de-planta/widgets/widget-5.yaml
  4: dashboards/dashboard-general-de-planta/widgets/widget-6.yaml
  5: dashboards/dashboard-general-de-planta/widgets/widget-7.yaml
  6: dashboards/dashboard-general-de-planta/widgets/widget-8.yaml
  9: dashboards/dashboard-general-de-planta/widgets/widget-9.yaml
  2: dashboards/grafiques-puntuals/widgets/widget.yaml
  3: dashboards/grafiques-puntuals/widgets/widget-2.yaml
  30: dashboards/dashboard-general-de-planta/widgets/widget-10.yaml
  25: dashboards/grafiques-puntuals/widgets/widget-3.yaml
  31: dashboards/grafiques-puntuals/widgets/widget-4.yaml
  32: dashboards/grafiques-puntuals/widgets/widget-5.yaml
  33: dashboards/dashboard-general-de-planta/widgets/widget-5.yaml
  34: dashboards/grafiques-puntuals/widgets/widget-6.yaml
  37: dashboards/sandbox/widgets/widget.yaml
  35: dashboards/dashboard-general-de-planta/widgets/widget-11.yaml
  39: dashboards/grafiques-puntuals/widgets/widget-7.yaml
  44: dashboards/dashboard-combinat/widgets/widget.yaml
  46: dashboards/dashboard-combinat/widgets/widget-2.yaml
  45: dashboards/dashboard-combinat/widgets/widget-3.yaml
  41: dashboards/dashboard-combinat/widgets/widget-4.yaml
  42: dashboards/dashboard-combinat/widgets/widget-5.yaml
  49: dashboards/dashboard-combinat/widgets/widget-6.yaml
  50: dashboards/dashboard-combinat/widgets/widget-7.yaml
  40: dashboards/dashboard-dinamic-de-planta/widgets/widget-5.yaml
  53: dashboards/dashboard-combinat/widgets/widget-8.yaml
  54: dashboards/dashboard-dinamic-de-planta/widgets/widget-6.yaml
  51: dashboards/dashboard-general-de-planta/widgets/widget-5.yaml
  56: dashboards/dashboard-general-de-planta/widgets/widget-12.yaml
