name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Tests plantmonitor"
    steps:
      - uses: actions/checkout@v2
      - name: Hello plants!
        run: echo "Hello!!!"
      - name: more, env vars etc
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"
